export const ShopActionTypes = {
  FETCH_COLLECTIONS_LOADING: 'FETCH_COLLECTIONS_LOADING',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  SEARCH_COLLECTIONS: 'SEARCH_COLLECTIONS'
};
